#!/bin/bash

# xrandr --output VGA1 --primary --output LVDS1 --off
# xrandr --output LVDS1 --auto --pos 0x0 --output VGA1 --primary --auto --pos 1920x0 --left-of LVDS1

while getopts 'aml' OPTION; do
    case "$OPTION" in
        a)
            xrandr --output LVDS1 --auto --pos 0x0 --output VGA1 --primary --auto --pos 1920x0 --left-of LVDS1
            ;;
        m)
            xrandr --output VGA1 --auto --primary --output LVDS1 --off
            ;;
        l)
            xrandr --output LVDS1 --auto --primary --output VGA1 --off
            ;;
        *)
            echo "monitor: $(basename $0) [-l] [-m] [-ml]" >&2
            exit 1
            ;;
    esac
done
